name: "Build/Publish"
run-name: "Build/Publish : mgarnier11/devcontainer-base:${{ github.sha }}"
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: linux/${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Build Docker image
        env:
          TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
        run: |
          docker build \
          --file Dockerfile \
          --tag mgarnier11/github-runner:${{ matrix.platform }} \
          .

      - name: Push Docker image
        run: |
          docker push 'mgarnier11/github-runner:${{ matrix.platform }}'
